# Generated by cpp11: do not edit by hand

ols_mat <- function(y, x) {
  .Call(`_cpp11blazetest_ols_mat`, y, x)
}

ols_vec <- function(y, x) {
  .Call(`_cpp11blazetest_ols_vec`, y, x)
}

eigen_sym_mat_no_wrapper <- function(x) {
  .Call(`_cpp11blazetest_eigen_sym_mat_no_wrapper`, x)
}

eigen_sym_dbl_no_wrapper <- function(x) {
  .Call(`_cpp11blazetest_eigen_sym_dbl_no_wrapper`, x)
}

eigen_gen_mat_complex_wrapper <- function(x) {
  .Call(`_cpp11blazetest_eigen_gen_mat_complex_wrapper`, x)
}

eigen_gen_dbl_complex_wrapper <- function(x) {
  .Call(`_cpp11blazetest_eigen_gen_dbl_complex_wrapper`, x)
}

eigen_gen_mat_no_wrapper <- function(x) {
  .Call(`_cpp11blazetest_eigen_gen_mat_no_wrapper`, x)
}

eigen_gen_dbl_no_wrapper <- function(x) {
  .Call(`_cpp11blazetest_eigen_gen_dbl_no_wrapper`, x)
}

chol_mat <- function(x) {
  .Call(`_cpp11blazetest_chol_mat`, x)
}

ols_qr_mat <- function(y, x) {
  .Call(`_cpp11blazetest_ols_qr_mat`, y, x)
}

ols_qr_dbl <- function(y, x) {
  .Call(`_cpp11blazetest_ols_qr_dbl`, y, x)
}

capm <- function(r, m, f) {
  .Call(`_cpp11blazetest_capm`, r, m, f)
}

typedef_Col_double <- function(x) {
  .Call(`_cpp11blazetest_typedef_Col_double`, x)
}

typedef_Col_int <- function(x) {
  .Call(`_cpp11blazetest_typedef_Col_int`, x)
}

typedef_Mat_double <- function(x) {
  .Call(`_cpp11blazetest_typedef_Mat_double`, x)
}

typedef_Mat_int <- function(x) {
  .Call(`_cpp11blazetest_typedef_Mat_int`, x)
}
